### ISSUE TITLE
Should update the releases.txt

### ISSUE THREAD

**Issue by lucascarvalho** [globocom/pluct#33]

**Comment by raphamorim** [comment]
Can we close this issue @ricobl ?

**Comment by lucascarvalho** [comment]
@raphamorim, the `release.txt` still not up to date.

**Comment by ricobl** [comment]
@raphamorim / @lucascarvalho: as we're not taking the time to update the file there's no point in keeping it outdated, I've removed it.

**Comment by raphamorim** [comment]
👍
